[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path = 'cache_forge'
ast = true
build_info = true
extra_output = ["storageLayout"]
sender = "0xA0FCc0Ef2E8624797Ff20c38725748024bca67A3"
fs_permissions = [{ access = "read", path = "./" }]

[rpc_endpoints]
arbitrumFork = 'https://virtual.arbitrum.rpc.tenderly.co/'
arbitrum = 'https://arb1.arbitrum.io/rpc'